In [28]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

In [29]:
type(mnist.load_data())

tuple

In [30]:
(x_train,y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(x_test.shape)


(60000, 28, 28)
(10000, 28, 28)


In [31]:
x_train = np.expand_dims(x_train, axis=-1).astype('float32')/255.0
print(x_train.shape)

(60000, 28, 28, 1)


In [32]:
x_test = np.expand_dims(x_test, axis=-1).astype('float32')/255.0
print(x_test.shape)

(10000, 28, 28, 1)


In [33]:
print("before : ", y_train.shape)
print(y_train)
y_train = to_categorical(y_train, 10)
print("after : ", y_train.shape)
print(y_train)


before :  (60000,)
[5 0 4 ... 5 6 8]
after :  (60000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [34]:
print("before : ", y_test.shape)
print(y_test)
y_test = to_categorical(y_test, 10)
print("after : ", y_test.shape)
print(y_test)


before :  (10000,)
[7 2 1 ... 4 5 6]
after :  (10000, 10)
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
#simple cnn model

model = Sequential([
    Conv2D(10,(3,3),activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((2,2)),
    Flatten(),
    Dense(10, activation='softmax')
])

In [36]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [39]:
model.fit(x_train,y_train, epochs=3,batch_size=64, validation_split=0.2)

Epoch 1/3
750/750 [==============================] - 11s 14ms/step - loss: 0.0710 - accuracy: 0.9795 - val_loss: 0.0829 - val_accuracy: 0.9755
Epoch 2/3
750/750 [==============================] - 11s 15ms/step - loss: 0.0635 - accuracy: 0.9814 - val_loss: 0.0708 - val_accuracy: 0.9785
Epoch 3/3
750/750 [==============================] - 11s 15ms/step - loss: 0.0587 - accuracy: 0.9832 - val_loss: 0.0699 - val_accuracy: 0.9791


In [38]:
test_loss, test_acc = model.evaluate(x_test,y_test)
print(f'test accuracy:{test_acc*100:.2f}%')

313/313 [==============================] - 1s 3ms/step - loss: 0.0764 - accuracy: 0.9758
test accuracy:97.58%
